#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# start check console.* and debugger in file has changed pre-commit

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-commit hook...${no_color}\n"

FILES_PATTERN='\.(ts|vue)(\..+)?$'
FORBIDDEN='console\.[clear|dir|log|info|warn|error]\|debugger'

#check for console debugger references in your code

if git diff --cached --name-only | \
  grep -E $FILES_PATTERN | \
  xargs grep --with-filename -n $FORBIDDEN | \
  grep -v '//';
then
  echo -e "\n${red}COMMIT REJECTED!  Found console.* or debugger. Please remove them before committing.\n${no_color}"
  exit 1;
fi
echo -e "${green}Git pre-commit hook was successful!${no_color}\n"
exit 0;

# end check console.* and debugger in file has changed pre-commit

npx lint-staged
